
package view;

import DAO.FuncionarioDAO;
import DTO.FuncionarioDTO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.lang.NumberFormatException;
/**
 *
 * @author Felipe
 */
public class viewFuncionario extends javax.swing.JFrame {

    FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();
    FuncionarioDAO objfuncionarioDAO = new FuncionarioDAO();
    /**
     * Creates new form viewFuncionario
     */
    public viewFuncionario() {
        initComponents();
        pesquisarListaDeFuncionario();
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEnderecoFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcodigoFuncionario = new javax.swing.JTextField();
        bttnCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        bttnAlterar = new javax.swing.JButton();
        bttnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcargoFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsalarioFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcpfFuncionario = new javax.swing.JTextField();
        txttelefoneFuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bttncarregarCampos = new javax.swing.JButton();
        bttnLimpar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Código:");

        txtcodigoFuncionario.setEditable(false);

        bttnCadastrar.setText("Cadastrar");
        bttnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastrarActionPerformed(evt);
            }
        });

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "ENDEREÇO", "CARGO", "SALÁRIO", "CPF", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionario);
        if (tabelaFuncionario.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionario.getColumnModel().getColumn(0).setMinWidth(60);
            tabelaFuncionario.getColumnModel().getColumn(0).setPreferredWidth(60);
            tabelaFuncionario.getColumnModel().getColumn(0).setMaxWidth(60);
            tabelaFuncionario.getColumnModel().getColumn(1).setMinWidth(200);
            tabelaFuncionario.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaFuncionario.getColumnModel().getColumn(1).setMaxWidth(200);
            tabelaFuncionario.getColumnModel().getColumn(2).setMinWidth(250);
            tabelaFuncionario.getColumnModel().getColumn(2).setPreferredWidth(250);
            tabelaFuncionario.getColumnModel().getColumn(2).setMaxWidth(250);
            tabelaFuncionario.getColumnModel().getColumn(4).setMinWidth(80);
            tabelaFuncionario.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabelaFuncionario.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        bttnAlterar.setText("Alterar");
        bttnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAlterarActionPerformed(evt);
            }
        });

        bttnExcluir.setText("Excluir");
        bttnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Cargo:");

        jLabel6.setText("Salario:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Telefone:");

        bttncarregarCampos.setText("Carregar ");
        bttncarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttncarregarCamposActionPerformed(evt);
            }
        });

        bttnLimpar.setText("Limpar");
        bttnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtcodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtsalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEnderecoFuncionario)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(138, 138, 138)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(txtcargoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txttelefoneFuncionario))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bttnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttncarregarCampos)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtsalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAlterar)
                    .addComponent(bttnExcluir)
                    .addComponent(bttncarregarCampos)
                    .addComponent(bttnLimpar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastrarActionPerformed
        cadastrarFuncionario();   
        pesquisarListaDeFuncionario();
        limparDados();
    }//GEN-LAST:event_bttnCadastrarActionPerformed

    private void bttncarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttncarregarCamposActionPerformed
      carregarCamposFuncionario();
    }//GEN-LAST:event_bttncarregarCamposActionPerformed

    private void bttnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_bttnLimparActionPerformed

    private void bttnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAlterarActionPerformed
        if (txtcodigoFuncionario.getText().isEmpty() || txtNomeFuncionario.getText().isEmpty() || txtEnderecoFuncionario.getText().isEmpty() || txtcargoFuncionario.getText().isEmpty() || txtsalarioFuncionario.getText().isEmpty() || txtcpfFuncionario.getText().isEmpty() || txttelefoneFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vazios, para altear clique primeiro em carregar. ");
        } else {
            alterarFuncionario();
        }
        pesquisarListaDeFuncionario();
        limparDados();

    }//GEN-LAST:event_bttnAlterarActionPerformed

    private void bttnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExcluirActionPerformed
        excluirFuncionario();
        pesquisarListaDeFuncionario();
        limparDados();
    }//GEN-LAST:event_bttnExcluirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAlterar;
    private javax.swing.JButton bttnCadastrar;
    private javax.swing.JButton bttnExcluir;
    private javax.swing.JButton bttnLimpar;
    private javax.swing.JButton bttncarregarCampos;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTextField txtEnderecoFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtcargoFuncionario;
    private javax.swing.JTextField txtcodigoFuncionario;
    private javax.swing.JTextField txtcpfFuncionario;
    private javax.swing.JTextField txtsalarioFuncionario;
    private javax.swing.JTextField txttelefoneFuncionario;
    // End of variables declaration//GEN-END:variables

    public void cadastrarFuncionario(){
         objFuncionarioDTO = new FuncionarioDTO();
      
      objFuncionarioDTO.setNome_funcionario(txtNomeFuncionario.getText());
      objFuncionarioDTO.setCpf_funcionario(txtcpfFuncionario.getText());
      objFuncionarioDTO.setTelefone_funcionario(txttelefoneFuncionario.getText());
      objFuncionarioDTO.setSalario(Double.parseDouble(txtsalarioFuncionario.getText()));
      objFuncionarioDTO.setEndereco_funcionario(txtEnderecoFuncionario.getText());
      objFuncionarioDTO.setCargo_funcionario(txtcargoFuncionario.getText());
      
      
      
      
      objfuncionarioDAO = new FuncionarioDAO();
      objfuncionarioDAO.cadastrarFuncionario(objFuncionarioDTO);
      
    }
    public void limparDados() {
        txtNomeFuncionario.setText("");
        txtcargoFuncionario.setText("");
        txtsalarioFuncionario.setText("");
        txtEnderecoFuncionario.setText("");
        txtcpfFuncionario.setText("");
        txttelefoneFuncionario.setText("");
        txtcodigoFuncionario.setText("");
        txtNomeFuncionario.requestFocus();
    }
    
    public void pesquisarListaDeFuncionario() {

        try {
            objfuncionarioDAO = new FuncionarioDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFuncionario.getModel();
            model.setNumRows(0);

            ArrayList<FuncionarioDTO> lista = objfuncionarioDAO.pesquisarFuncionario();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_funcionario(),
                    lista.get(num).getNome_funcionario(),
                    lista.get(num).getEndereco_funcionario(),
                    lista.get(num).getCargo_funcionario(),
                    lista.get(num).getSalario(),
                    lista.get(num).getCpf_funcionario(),
                    lista.get(num).getTelefone_funcionario()

                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "pesquisarListaDeFuncionario VIEW     :" + erro);
        }
    }
    
    private void carregarCamposFuncionario(){
        int setar = tabelaFuncionario.getSelectedRow();
        
        txtcodigoFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar, 0).toString());
        txtNomeFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,1 ).toString());
        txtcpfFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,2).toString());
        txttelefoneFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,3).toString());
        txtsalarioFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,4 ).toString());
        txtEnderecoFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,5).toString());
        txtcargoFuncionario.setText(tabelaFuncionario.getModel().getValueAt(setar,6).toString());
    }
    
    private void alterarFuncionario(){
        FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();
        
       
        
        objFuncionarioDTO.setId_funcionario(Integer.parseInt(txtcodigoFuncionario.getText()));
        objFuncionarioDTO.setNome_funcionario(txtNomeFuncionario.getText());
        objFuncionarioDTO.setCpf_funcionario(txtcpfFuncionario.getText());
        objFuncionarioDTO.setTelefone_funcionario(txttelefoneFuncionario.getText());
        objFuncionarioDTO.setSalario(Double.parseDouble(txtsalarioFuncionario.getText()));
        objFuncionarioDTO.setEndereco_funcionario(txtEnderecoFuncionario.getText());
        objFuncionarioDTO.setCargo_funcionario(txtcargoFuncionario.getText());
       
        objfuncionarioDAO = new FuncionarioDAO();
        objfuncionarioDAO.alterarFuncionario(objFuncionarioDTO);
            
    }
    
    private void excluirFuncionario(){
        objFuncionarioDTO = new FuncionarioDTO();
        
        objFuncionarioDTO.setId_funcionario(Integer.parseInt(txtcodigoFuncionario.getText()));
       
        
        objfuncionarioDAO = new FuncionarioDAO();
        objfuncionarioDAO.excluirFuncionario(objFuncionarioDTO);
                
        
    }

}